// svelte-todomvc-80/App.svelte
<script>
	import TodoMVC1 from './components/todomvc1.svelte';
	import TodoMVC2 from './components/todomvc2.svelte';
	import TodoMVC3 from './components/todomvc3.svelte';
	import TodoMVC4 from './components/todomvc4.svelte';
	import TodoMVC5 from './components/todomvc5.svelte';
	import TodoMVC6 from './components/todomvc6.svelte';
	import TodoMVC7 from './components/todomvc7.svelte';
	import TodoMVC8 from './components/todomvc8.svelte';
	import TodoMVC9 from './components/todomvc9.svelte';
	import TodoMVC10 from './components/todomvc10.svelte';
	import TodoMVC11 from './components/todomvc11.svelte';
	import TodoMVC12 from './components/todomvc12.svelte';
	import TodoMVC13 from './components/todomvc13.svelte';
	import TodoMVC14 from './components/todomvc14.svelte';
	import TodoMVC15 from './components/todomvc15.svelte';
	import TodoMVC16 from './components/todomvc16.svelte';
	import TodoMVC17 from './components/todomvc17.svelte';
	import TodoMVC18 from './components/todomvc18.svelte';
	import TodoMVC19 from './components/todomvc19.svelte';
	import TodoMVC20 from './components/todomvc20.svelte';
	import TodoMVC21 from './components/todomvc21.svelte';
	import TodoMVC22 from './components/todomvc22.svelte';
	import TodoMVC23 from './components/todomvc23.svelte';
	import TodoMVC24 from './components/todomvc24.svelte';
	import TodoMVC25 from './components/todomvc25.svelte';
	import TodoMVC26 from './components/todomvc26.svelte';
	import TodoMVC27 from './components/todomvc27.svelte';
	import TodoMVC28 from './components/todomvc28.svelte';
	import TodoMVC29 from './components/todomvc29.svelte';
	import TodoMVC30 from './components/todomvc30.svelte';
	import TodoMVC31 from './components/todomvc31.svelte';
	import TodoMVC32 from './components/todomvc32.svelte';
	import TodoMVC33 from './components/todomvc33.svelte';
	import TodoMVC34 from './components/todomvc34.svelte';
	import TodoMVC35 from './components/todomvc35.svelte';
	import TodoMVC36 from './components/todomvc36.svelte';
	import TodoMVC37 from './components/todomvc37.svelte';
	import TodoMVC38 from './components/todomvc38.svelte';
	import TodoMVC39 from './components/todomvc39.svelte';
	import TodoMVC40 from './components/todomvc40.svelte';
	import TodoMVC41 from './components/todomvc41.svelte';
	import TodoMVC42 from './components/todomvc42.svelte';
	import TodoMVC43 from './components/todomvc43.svelte';
	import TodoMVC44 from './components/todomvc44.svelte';
	import TodoMVC45 from './components/todomvc45.svelte';
	import TodoMVC46 from './components/todomvc46.svelte';
	import TodoMVC47 from './components/todomvc47.svelte';
	import TodoMVC48 from './components/todomvc48.svelte';
	import TodoMVC49 from './components/todomvc49.svelte';
	import TodoMVC50 from './components/todomvc50.svelte';
	import TodoMVC51 from './components/todomvc51.svelte';
	import TodoMVC52 from './components/todomvc52.svelte';
	import TodoMVC53 from './components/todomvc53.svelte';
	import TodoMVC54 from './components/todomvc54.svelte';
	import TodoMVC55 from './components/todomvc55.svelte';
	import TodoMVC56 from './components/todomvc56.svelte';
	import TodoMVC57 from './components/todomvc57.svelte';
	import TodoMVC58 from './components/todomvc58.svelte';
	import TodoMVC59 from './components/todomvc59.svelte';
	import TodoMVC60 from './components/todomvc60.svelte';
	import TodoMVC61 from './components/todomvc61.svelte';
	import TodoMVC62 from './components/todomvc62.svelte';
	import TodoMVC63 from './components/todomvc63.svelte';
	import TodoMVC64 from './components/todomvc64.svelte';
	import TodoMVC65 from './components/todomvc65.svelte';
	import TodoMVC66 from './components/todomvc66.svelte';
	import TodoMVC67 from './components/todomvc67.svelte';
	import TodoMVC68 from './components/todomvc68.svelte';
	import TodoMVC69 from './components/todomvc69.svelte';
	import TodoMVC70 from './components/todomvc70.svelte';
	import TodoMVC71 from './components/todomvc71.svelte';
	import TodoMVC72 from './components/todomvc72.svelte';
	import TodoMVC73 from './components/todomvc73.svelte';
	import TodoMVC74 from './components/todomvc74.svelte';
	import TodoMVC75 from './components/todomvc75.svelte';
	import TodoMVC76 from './components/todomvc76.svelte';
	import TodoMVC77 from './components/todomvc77.svelte';
	import TodoMVC78 from './components/todomvc78.svelte';
	import TodoMVC79 from './components/todomvc79.svelte';
	import TodoMVC80 from './components/todomvc80.svelte';
</script>

<TodoMVC1 />
<TodoMVC2 />
<TodoMVC3 />
<TodoMVC4 />
<TodoMVC5 />
<TodoMVC6 />
<TodoMVC7 />
<TodoMVC8 />
<TodoMVC9 />
<TodoMVC10 />
<TodoMVC11 />
<TodoMVC12 />
<TodoMVC13 />
<TodoMVC14 />
<TodoMVC15 />
<TodoMVC16 />
<TodoMVC17 />
<TodoMVC18 />
<TodoMVC19 />
<TodoMVC20 />
<TodoMVC21 />
<TodoMVC22 />
<TodoMVC23 />
<TodoMVC24 />
<TodoMVC25 />
<TodoMVC26 />
<TodoMVC27 />
<TodoMVC28 />
<TodoMVC29 />
<TodoMVC30 />
<TodoMVC31 />
<TodoMVC32 />
<TodoMVC33 />
<TodoMVC34 />
<TodoMVC35 />
<TodoMVC36 />
<TodoMVC37 />
<TodoMVC38 />
<TodoMVC39 />
<TodoMVC40 />
<TodoMVC41 />
<TodoMVC42 />
<TodoMVC43 />
<TodoMVC44 />
<TodoMVC45 />
<TodoMVC46 />
<TodoMVC47 />
<TodoMVC48 />
<TodoMVC49 />
<TodoMVC50 />
<TodoMVC51 />
<TodoMVC52 />
<TodoMVC53 />
<TodoMVC54 />
<TodoMVC55 />
<TodoMVC56 />
<TodoMVC57 />
<TodoMVC58 />
<TodoMVC59 />
<TodoMVC60 />
<TodoMVC61 />
<TodoMVC62 />
<TodoMVC63 />
<TodoMVC64 />
<TodoMVC65 />
<TodoMVC66 />
<TodoMVC67 />
<TodoMVC68 />
<TodoMVC69 />
<TodoMVC70 />
<TodoMVC71 />
<TodoMVC72 />
<TodoMVC73 />
<TodoMVC74 />
<TodoMVC75 />
<TodoMVC76 />
<TodoMVC77 />
<TodoMVC78 />
<TodoMVC79 />
<TodoMVC80 />

// vue-todomvc-80/app.vue
<script setup>
import TodoMVC1 from './components/todomvc1.vue';
import TodoMVC2 from './components/todomvc2.vue';
import TodoMVC3 from './components/todomvc3.vue';
import TodoMVC4 from './components/todomvc4.vue';
import TodoMVC5 from './components/todomvc5.vue';
import TodoMVC6 from './components/todomvc6.vue';
import TodoMVC7 from './components/todomvc7.vue';
import TodoMVC8 from './components/todomvc8.vue';
import TodoMVC9 from './components/todomvc9.vue';
import TodoMVC10 from './components/todomvc10.vue';
import TodoMVC11 from './components/todomvc11.vue';
import TodoMVC12 from './components/todomvc12.vue';
import TodoMVC13 from './components/todomvc13.vue';
import TodoMVC14 from './components/todomvc14.vue';
import TodoMVC15 from './components/todomvc15.vue';
import TodoMVC16 from './components/todomvc16.vue';
import TodoMVC17 from './components/todomvc17.vue';
import TodoMVC18 from './components/todomvc18.vue';
import TodoMVC19 from './components/todomvc19.vue';
import TodoMVC20 from './components/todomvc20.vue';
import TodoMVC21 from './components/todomvc21.vue';
import TodoMVC22 from './components/todomvc22.vue';
import TodoMVC23 from './components/todomvc23.vue';
import TodoMVC24 from './components/todomvc24.vue';
import TodoMVC25 from './components/todomvc25.vue';
import TodoMVC26 from './components/todomvc26.vue';
import TodoMVC27 from './components/todomvc27.vue';
import TodoMVC28 from './components/todomvc28.vue';
import TodoMVC29 from './components/todomvc29.vue';
import TodoMVC30 from './components/todomvc30.vue';
import TodoMVC31 from './components/todomvc31.vue';
import TodoMVC32 from './components/todomvc32.vue';
import TodoMVC33 from './components/todomvc33.vue';
import TodoMVC34 from './components/todomvc34.vue';
import TodoMVC35 from './components/todomvc35.vue';
import TodoMVC36 from './components/todomvc36.vue';
import TodoMVC37 from './components/todomvc37.vue';
import TodoMVC38 from './components/todomvc38.vue';
import TodoMVC39 from './components/todomvc39.vue';
import TodoMVC40 from './components/todomvc40.vue';
import TodoMVC41 from './components/todomvc41.vue';
import TodoMVC42 from './components/todomvc42.vue';
import TodoMVC43 from './components/todomvc43.vue';
import TodoMVC44 from './components/todomvc44.vue';
import TodoMVC45 from './components/todomvc45.vue';
import TodoMVC46 from './components/todomvc46.vue';
import TodoMVC47 from './components/todomvc47.vue';
import TodoMVC48 from './components/todomvc48.vue';
import TodoMVC49 from './components/todomvc49.vue';
import TodoMVC50 from './components/todomvc50.vue';
import TodoMVC51 from './components/todomvc51.vue';
import TodoMVC52 from './components/todomvc52.vue';
import TodoMVC53 from './components/todomvc53.vue';
import TodoMVC54 from './components/todomvc54.vue';
import TodoMVC55 from './components/todomvc55.vue';
import TodoMVC56 from './components/todomvc56.vue';
import TodoMVC57 from './components/todomvc57.vue';
import TodoMVC58 from './components/todomvc58.vue';
import TodoMVC59 from './components/todomvc59.vue';
import TodoMVC60 from './components/todomvc60.vue';
import TodoMVC61 from './components/todomvc61.vue';
import TodoMVC62 from './components/todomvc62.vue';
import TodoMVC63 from './components/todomvc63.vue';
import TodoMVC64 from './components/todomvc64.vue';
import TodoMVC65 from './components/todomvc65.vue';
import TodoMVC66 from './components/todomvc66.vue';
import TodoMVC67 from './components/todomvc67.vue';
import TodoMVC68 from './components/todomvc68.vue';
import TodoMVC69 from './components/todomvc69.vue';
import TodoMVC70 from './components/todomvc70.vue';
import TodoMVC71 from './components/todomvc71.vue';
import TodoMVC72 from './components/todomvc72.vue';
import TodoMVC73 from './components/todomvc73.vue';
import TodoMVC74 from './components/todomvc74.vue';
import TodoMVC75 from './components/todomvc75.vue';
import TodoMVC76 from './components/todomvc76.vue';
import TodoMVC77 from './components/todomvc77.vue';
import TodoMVC78 from './components/todomvc78.vue';
import TodoMVC79 from './components/todomvc79.vue';
import TodoMVC80 from './components/todomvc80.vue';
</script>

<template>
  <TodoMVC1 />
  <TodoMVC2 />
  <TodoMVC3 />
  <TodoMVC4 />
  <TodoMVC5 />
  <TodoMVC6 />
  <TodoMVC7 />
  <TodoMVC8 />
  <TodoMVC9 />
  <TodoMVC10 />
  <TodoMVC11 />
  <TodoMVC12 />
  <TodoMVC13 />
  <TodoMVC14 />
  <TodoMVC15 />
  <TodoMVC16 />
  <TodoMVC17 />
  <TodoMVC18 />
  <TodoMVC19 />
  <TodoMVC20 />
  <TodoMVC21 />
  <TodoMVC22 />
  <TodoMVC23 />
  <TodoMVC24 />
  <TodoMVC25 />
  <TodoMVC26 />
  <TodoMVC27 />
  <TodoMVC28 />
  <TodoMVC29 />
  <TodoMVC30 />
  <TodoMVC31 />
  <TodoMVC32 />
  <TodoMVC33 />
  <TodoMVC34 />
  <TodoMVC35 />
  <TodoMVC36 />
  <TodoMVC37 />
  <TodoMVC38 />
  <TodoMVC39 />
  <TodoMVC40 />
  <TodoMVC41 />
  <TodoMVC42 />
  <TodoMVC43 />
  <TodoMVC44 />
  <TodoMVC45 />
  <TodoMVC46 />
  <TodoMVC47 />
  <TodoMVC48 />
  <TodoMVC49 />
  <TodoMVC50 />
  <TodoMVC51 />
  <TodoMVC52 />
  <TodoMVC53 />
  <TodoMVC54 />
  <TodoMVC55 />
  <TodoMVC56 />
  <TodoMVC57 />
  <TodoMVC58 />
  <TodoMVC59 />
  <TodoMVC60 />
  <TodoMVC61 />
  <TodoMVC62 />
  <TodoMVC63 />
  <TodoMVC64 />
  <TodoMVC65 />
  <TodoMVC66 />
  <TodoMVC67 />
  <TodoMVC68 />
  <TodoMVC69 />
  <TodoMVC70 />
  <TodoMVC71 />
  <TodoMVC72 />
  <TodoMVC73 />
  <TodoMVC74 />
  <TodoMVC75 />
  <TodoMVC76 />
  <TodoMVC77 />
  <TodoMVC78 />
  <TodoMVC79 />
  <TodoMVC80 />
</template>
